siteConfig:
  title: Latex Diagrams
build:
  publicUrl: /
plugins:
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-search
  - resolve: saber-plugin-copy-code
    options: 
      statusAttribute: title
      buttonStyle: 
        background-color: red